title: Growth Study Guide
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://growthecon.com/StudyGuide/" 
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Study Guide on GitHub":
    - "https://github.com/dvollrath/StudyGuide"
ga_tracking: UA-72839737-1
ga_tracking_anonymize_ip: true
