title: Growth Study Guide
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Study Guide on GitHub":
    - "https://github.com/dvollrath/StudyGuide"
ga_tracking: UA-72839737-1
ga_tracking_anonymize_ip: true
rel_url: false
button: true
heading_anchors: false